//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Taxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Taxes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Taxes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied on.
        /// </summary>
        internal static string detailsgridtaxappliedon {
            get {
                return ResourceManager.GetString("detailsgridtaxappliedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string detailsgridtaxfrom {
            get {
                return ResourceManager.GetString("detailsgridtaxfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax %.
        /// </summary>
        internal static string detailsgridtaxpercent {
            get {
                return ResourceManager.GetString("detailsgridtaxpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string detailsgridtaxto {
            get {
                return ResourceManager.GetString("detailsgridtaxto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string detailsgridtaxtype {
            get {
                return ResourceManager.GetString("detailsgridtaxtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string gridtaxcode {
            get {
                return ResourceManager.GetString("gridtaxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Key.
        /// </summary>
        internal static string gridtaxkey {
            get {
                return ResourceManager.GetString("gridtaxkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string gridtaxname {
            get {
                return ResourceManager.GetString("gridtaxname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string lblCreatetaxes {
            get {
                return ResourceManager.GetString("lblCreatetaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax code*.
        /// </summary>
        internal static string lbltaxcode {
            get {
                return ResourceManager.GetString("lbltaxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name*.
        /// </summary>
        internal static string lbltaxname {
            get {
                return ResourceManager.GetString("lbltaxname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Add .
        /// </summary>
        internal static string lnkAddrow {
            get {
                return ResourceManager.GetString("lnkAddrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Tax Code.
        /// </summary>
        internal static string reqvtaxcode {
            get {
                return ResourceManager.GetString("reqvtaxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code must be unique.Please enter a unique tax code.
        /// </summary>
        internal static string reqvtaxcodeUNQ {
            get {
                return ResourceManager.GetString("reqvtaxcodeUNQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Tax Name.
        /// </summary>
        internal static string reqvtxttaxname {
            get {
                return ResourceManager.GetString("reqvtxttaxname", resourceCulture);
            }
        }
    }
}
