//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Client", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        internal static string gridclientsactive {
            get {
                return ResourceManager.GetString("gridclientsactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string gridclientsaddress1 {
            get {
                return ResourceManager.GetString("gridclientsaddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string gridclientsaddress2 {
            get {
                return ResourceManager.GetString("gridclientsaddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string gridclientscity {
            get {
                return ResourceManager.GetString("gridclientscity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Code.
        /// </summary>
        internal static string gridclientscode {
            get {
                return ResourceManager.GetString("gridclientscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string gridclientscontactname {
            get {
                return ResourceManager.GetString("gridclientscontactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string gridclientscountry {
            get {
                return ResourceManager.GetString("gridclientscountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Designation.
        /// </summary>
        internal static string gridclientsdesignation {
            get {
                return ResourceManager.GetString("gridclientsdesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        internal static string gridclientsname {
            get {
                return ResourceManager.GetString("gridclientsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string gridclientsstate {
            get {
                return ResourceManager.GetString("gridclientsstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string gridclientszip {
            get {
                return ResourceManager.GetString("gridclientszip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lbladdresscity {
            get {
                return ResourceManager.GetString("lbladdresscity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lbladdresscountry {
            get {
                return ResourceManager.GetString("lbladdresscountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string lbladdressline1 {
            get {
                return ResourceManager.GetString("lbladdressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string lbladdressline2 {
            get {
                return ResourceManager.GetString("lbladdressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string lbladdressstate {
            get {
                return ResourceManager.GetString("lbladdressstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string lbladdresszip {
            get {
                return ResourceManager.GetString("lbladdresszip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string lblbilladdress1 {
            get {
                return ResourceManager.GetString("lblbilladdress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string lblbilladdress2 {
            get {
                return ResourceManager.GetString("lblbilladdress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblbillcity {
            get {
                return ResourceManager.GetString("lblbillcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblbillcountry {
            get {
                return ResourceManager.GetString("lblbillcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill info same as Address info.
        /// </summary>
        internal static string lblbillinfosame {
            get {
                return ResourceManager.GetString("lblbillinfosame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string lblbillstate {
            get {
                return ResourceManager.GetString("lblbillstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string lblbillzip {
            get {
                return ResourceManager.GetString("lblbillzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Code*.
        /// </summary>
        internal static string lblclientcode {
            get {
                return ResourceManager.GetString("lblclientcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Designation.
        /// </summary>
        internal static string lblclientcontactdesignation {
            get {
                return ResourceManager.GetString("lblclientcontactdesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string lblclientcontactname {
            get {
                return ResourceManager.GetString("lblclientcontactname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name*.
        /// </summary>
        internal static string lblclientname {
            get {
                return ResourceManager.GetString("lblclientname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string lblCreateClients {
            get {
                return ResourceManager.GetString("lblCreateClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active*.
        /// </summary>
        internal static string lblIsactive {
            get {
                return ResourceManager.GetString("lblIsactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id Should be Unique.
        /// </summary>
        internal static string reqvUnqclientcode {
            get {
                return ResourceManager.GetString("reqvUnqclientcode", resourceCulture);
            }
        }
    }
}
