//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Projects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Projects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Projects", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string gridclientname {
            get {
                return ResourceManager.GetString("gridclientname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string gridisactive {
            get {
                return ResourceManager.GetString("gridisactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code.
        /// </summary>
        internal static string gridprojectcode {
            get {
                return ResourceManager.GetString("gridprojectcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project KickOff Date.
        /// </summary>
        internal static string gridprojectkickoffdate {
            get {
                return ResourceManager.GetString("gridprojectkickoffdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string gridprojectname {
            get {
                return ResourceManager.GetString("gridprojectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner.
        /// </summary>
        internal static string gridprojectowner {
            get {
                return ResourceManager.GetString("gridprojectowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active*.
        /// </summary>
        internal static string lblactive {
            get {
                return ResourceManager.GetString("lblactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name*.
        /// </summary>
        internal static string lblclientname {
            get {
                return ResourceManager.GetString("lblclientname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string lblCreateProjects {
            get {
                return ResourceManager.GetString("lblCreateProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string lblistcaption {
            get {
                return ResourceManager.GetString("lblistcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code*.
        /// </summary>
        internal static string lblprojectcode {
            get {
                return ResourceManager.GetString("lblprojectcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project KickOff Date*.
        /// </summary>
        internal static string lblprojectkickoffdate {
            get {
                return ResourceManager.GetString("lblprojectkickoffdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name*.
        /// </summary>
        internal static string lblprojectname {
            get {
                return ResourceManager.GetString("lblprojectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Owner*.
        /// </summary>
        internal static string lblprojectowner {
            get {
                return ResourceManager.GetString("lblprojectowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter the Project Code.
        /// </summary>
        internal static string reqvprojectcode {
            get {
                return ResourceManager.GetString("reqvprojectcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter the Project name.
        /// </summary>
        internal static string reqvprojectname {
            get {
                return ResourceManager.GetString("reqvprojectname", resourceCulture);
            }
        }
    }
}
