//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Companies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Companies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Companies", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active*.
        /// </summary>
        internal static string lblactive {
            get {
                return ResourceManager.GetString("lblactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line1*.
        /// </summary>
        internal static string lbladdressline1 {
            get {
                return ResourceManager.GetString("lbladdressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line2.
        /// </summary>
        internal static string lbladdressline2 {
            get {
                return ResourceManager.GetString("lbladdressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line1*.
        /// </summary>
        internal static string lblbilladdressline1 {
            get {
                return ResourceManager.GetString("lblbilladdressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line2.
        /// </summary>
        internal static string lblbilladdressline2 {
            get {
                return ResourceManager.GetString("lblbilladdressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblbillcity {
            get {
                return ResourceManager.GetString("lblbillcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblbillcountry {
            get {
                return ResourceManager.GetString("lblbillcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string lblbillstate {
            get {
                return ResourceManager.GetString("lblbillstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string lblbillzip {
            get {
                return ResourceManager.GetString("lblbillzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblcity {
            get {
                return ResourceManager.GetString("lblcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code*.
        /// </summary>
        internal static string lblcompanycode {
            get {
                return ResourceManager.GetString("lblcompanycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name*.
        /// </summary>
        internal static string lblcompanyname {
            get {
                return ResourceManager.GetString("lblcompanyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblcountry {
            get {
                return ResourceManager.GetString("lblcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lblCreateCompanies {
            get {
                return ResourceManager.GetString("lblCreateCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desigination*.
        /// </summary>
        internal static string lbldesigination {
            get {
                return ResourceManager.GetString("lbldesigination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        internal static string lblname {
            get {
                return ResourceManager.GetString("lblname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Same as Company Address.
        /// </summary>
        internal static string lblsameinfo {
            get {
                return ResourceManager.GetString("lblsameinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string lblstate {
            get {
                return ResourceManager.GetString("lblstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string lblzip {
            get {
                return ResourceManager.GetString("lblzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Company Code.
        /// </summary>
        internal static string reqvcompanycode {
            get {
                return ResourceManager.GetString("reqvcompanycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Address Line1.
        /// </summary>
        internal static string reqvtxtaddressline1 {
            get {
                return ResourceManager.GetString("reqvtxtaddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleser Enter Billing Adress Line1.
        /// </summary>
        internal static string reqvtxtbilladdressline1 {
            get {
                return ResourceManager.GetString("reqvtxtbilladdressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Comapany Name .
        /// </summary>
        internal static string reqvtxtcompanyname {
            get {
                return ResourceManager.GetString("reqvtxtcompanyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Designation.
        /// </summary>
        internal static string reqvtxtdesigination {
            get {
                return ResourceManager.GetString("reqvtxtdesigination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name.
        /// </summary>
        internal static string reqvtxtname {
            get {
                return ResourceManager.GetString("reqvtxtname", resourceCulture);
            }
        }
    }
}
