//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero value should not be allowed..
        /// </summary>
        internal static string Alertzerovalue {
            get {
                return ResourceManager.GetString("Alertzerovalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Already Exists !!!.
        /// </summary>
        internal static string AlreadyExistMsg {
            get {
                return ResourceManager.GetString("AlreadyExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Files/App-Images.
        /// </summary>
        internal static string AppIconimagePath {
            get {
                return ResourceManager.GetString("AppIconimagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Application Type Already Exists for .
        /// </summary>
        internal static string ApplicationTypeExistMsg {
            get {
                return ResourceManager.GetString("ApplicationTypeExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string btnApprove {
            get {
                return ResourceManager.GetString("btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string btnAssign {
            get {
                return ResourceManager.GetString("btnAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string btnGenerate {
            get {
                return ResourceManager.GetString("btnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string btnPreview {
            get {
                return ResourceManager.GetString("btnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string btnReject {
            get {
                return ResourceManager.GetString("btnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnSearchClear {
            get {
                return ResourceManager.GetString("btnSearchClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show Calendar.
        /// </summary>
        internal static string CalendarAlt {
            get {
                return ResourceManager.GetString("CalendarAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show Calendar.
        /// </summary>
        internal static string CalendarAlt1 {
            get {
                return ResourceManager.GetString("CalendarAlt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The details have been updated / deleted by another User. Please review the page..
        /// </summary>
        internal static string ConcurrencyMsg {
            get {
                return ResourceManager.GetString("ConcurrencyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully !!!.
        /// </summary>
        internal static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete the record ?.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string gridAdd {
            get {
                return ResourceManager.GetString("gridAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrator.
        /// </summary>
        internal static string gridAdmin {
            get {
                return ResourceManager.GetString("gridAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string gridAmount {
            get {
                return ResourceManager.GetString("gridAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort.
        /// </summary>
        internal static string gridCohort {
            get {
                return ResourceManager.GetString("gridCohort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Points.
        /// </summary>
        internal static string gridDataPoints {
            get {
                return ResourceManager.GetString("gridDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string gridDelete {
            get {
                return ResourceManager.GetString("gridDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string gridDescription {
            get {
                return ResourceManager.GetString("gridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string gridEdit {
            get {
                return ResourceManager.GetString("gridEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit / View.
        /// </summary>
        internal static string gridEditView {
            get {
                return ResourceManager.GetString("gridEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gridName {
            get {
                return ResourceManager.GetString("gridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC Number.
        /// </summary>
        internal static string gridNRICNumber {
            get {
                return ResourceManager.GetString("gridNRICNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        internal static string gridProgramme {
            get {
                return ResourceManager.GetString("gridProgramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string gridSelect {
            get {
                return ResourceManager.GetString("gridSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        internal static string gridStudentID {
            get {
                return ResourceManager.GetString("gridStudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string gridStudentName {
            get {
                return ResourceManager.GetString("gridStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string gridView {
            get {
                return ResourceManager.GetString("gridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string gvActive {
            get {
                return ResourceManager.GetString("gvActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended.
        /// </summary>
        internal static string gvAttended {
            get {
                return ResourceManager.GetString("gvAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No..
        /// </summary>
        internal static string gvContactNumber {
            get {
                return ResourceManager.GetString("gvContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string gvenddate {
            get {
                return ResourceManager.GetString("gvenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC/Passport No..
        /// </summary>
        internal static string gvICPassportNo {
            get {
                return ResourceManager.GetString("gvICPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake.
        /// </summary>
        internal static string gvIntake {
            get {
                return ResourceManager.GetString("gvIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gvName {
            get {
                return ResourceManager.GetString("gvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        internal static string gvProgramme {
            get {
                return ResourceManager.GetString("gvProgramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string gvRemarks {
            get {
                return ResourceManager.GetString("gvRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string gvstartdate {
            get {
                return ResourceManager.GetString("gvstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string gvStatus {
            get {
                return ResourceManager.GetString("gvStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string gvSubject {
            get {
                return ResourceManager.GetString("gvSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Amount.
        /// </summary>
        internal static string lblActualAmount {
            get {
                return ResourceManager.GetString("lblActualAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line1.
        /// </summary>
        internal static string lblAddressLine1 {
            get {
                return ResourceManager.GetString("lblAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line2.
        /// </summary>
        internal static string lblAddressLine2 {
            get {
                return ResourceManager.GetString("lblAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line3.
        /// </summary>
        internal static string lblAddressLine3 {
            get {
                return ResourceManager.GetString("lblAddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Amount.
        /// </summary>
        internal static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumiputera.
        /// </summary>
        internal static string lblBumiputera {
            get {
                return ResourceManager.GetString("lblBumiputera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort.
        /// </summary>
        internal static string lblCohort {
            get {
                return ResourceManager.GetString("lblCohort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No..
        /// </summary>
        internal static string lblContactNo {
            get {
                return ResourceManager.GetString("lblContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees Amount.
        /// </summary>
        internal static string lblCurrentAmount {
            get {
                return ResourceManager.GetString("lblCurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Scheme.
        /// </summary>
        internal static string lblCurrentScheme {
            get {
                return ResourceManager.GetString("lblCurrentScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string lblDateofBirth {
            get {
                return ResourceManager.GetString("lblDateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string lblEMailAddress {
            get {
                return ResourceManager.GetString("lblEMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No.
        /// </summary>
        internal static string lblFaxNo {
            get {
                return ResourceManager.GetString("lblFaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string lblFemale {
            get {
                return ResourceManager.GetString("lblFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string lblGrade {
            get {
                return ResourceManager.GetString("lblGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Phone.
        /// </summary>
        internal static string lblHandPhone {
            get {
                return ResourceManager.GetString("lblHandPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake.
        /// </summary>
        internal static string lblIntake {
            get {
                return ResourceManager.GetString("lblIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string lblInternational {
            get {
                return ResourceManager.GetString("lblInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian/International.
        /// </summary>
        internal static string lblLocalForeign {
            get {
                return ResourceManager.GetString("lblLocalForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian.
        /// </summary>
        internal static string lblMalaysian {
            get {
                return ResourceManager.GetString("lblMalaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string lblMale {
            get {
                return ResourceManager.GetString("lblMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string lblMaritalStatus {
            get {
                return ResourceManager.GetString("lblMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Fees Amount.
        /// </summary>
        internal static string lblNetAmount {
            get {
                return ResourceManager.GetString("lblNetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC Number.
        /// </summary>
        internal static string lblNRICNumber {
            get {
                return ResourceManager.GetString("lblNRICNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string lblOthers {
            get {
                return ResourceManager.GetString("lblOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        internal static string lblPaid {
            get {
                return ResourceManager.GetString("lblPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        internal static string lblPassportNo {
            get {
                return ResourceManager.GetString("lblPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string lblPostCode {
            get {
                return ResourceManager.GetString("lblPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        internal static string lblProgramme {
            get {
                return ResourceManager.GetString("lblProgramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Values.
        /// </summary>
        internal static string lblPropertyHeader {
            get {
                return ResourceManager.GetString("lblPropertyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string lblReason {
            get {
                return ResourceManager.GetString("lblReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Amount.
        /// </summary>
        internal static string lblRefund {
            get {
                return ResourceManager.GetString("lblRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string lblRemarks {
            get {
                return ResourceManager.GetString("lblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarship.
        /// </summary>
        internal static string lblScholar {
            get {
                return ResourceManager.GetString("lblScholar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Firm.
        /// </summary>
        internal static string lblSearchHeader {
            get {
                return ResourceManager.GetString("lblSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        internal static string lblSemester {
            get {
                return ResourceManager.GetString("lblSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        internal static string lblStaffName {
            get {
                return ResourceManager.GetString("lblStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        internal static string lblStudentID {
            get {
                return ResourceManager.GetString("lblStudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string lblStudentName {
            get {
                return ResourceManager.GetString("lblStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No.
        /// </summary>
        internal static string lblTelephoneNo {
            get {
                return ResourceManager.GetString("lblTelephoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone(Home).
        /// </summary>
        internal static string lblTelephoneNoHome {
            get {
                return ResourceManager.GetString("lblTelephoneNoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone(Office).
        /// </summary>
        internal static string lblTelephoneNoOffice {
            get {
                return ResourceManager.GetString("lblTelephoneNoOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NRIC Number.
        /// </summary>
        internal static string mevNRICNumber {
            get {
                return ResourceManager.GetString("mevNRICNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload &quot;JPG&quot; or &quot;GIF&quot; or &quot;JPEG&quot; or &quot;PNG&quot; or &quot;PDF&quot; or &quot;doc&quot; or &quot;docx&quot; extension files only.
        /// </summary>
        internal static string msgWarningImagePDFWordType {
            get {
                return ResourceManager.GetString("msgWarningImagePDFWordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload &quot;JPG&quot; or &quot;GIF&quot; or &quot;JPEG&quot; or &quot;PNG&quot; extension files only.
        /// </summary>
        internal static string msgWarningImageType {
            get {
                return ResourceManager.GetString("msgWarningImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/NoAppImage.gif.
        /// </summary>
        internal static string NoAppImagePath {
            get {
                return ResourceManager.GetString("NoAppImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/user_icon.png.
        /// </summary>
        internal static string NoimagePath {
            get {
                return ResourceManager.GetString("NoimagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found !!!.
        /// </summary>
        internal static string NoRecordMsg {
            get {
                return ResourceManager.GetString("NoRecordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found for your search criteria..
        /// </summary>
        internal static string NoRecordSearch {
            get {
                return ResourceManager.GetString("NoRecordSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while generating the Report. Please try again !!!.
        /// </summary>
        internal static string ReportErrorMsg {
            get {
                return ResourceManager.GetString("ReportErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid Email Address !.
        /// </summary>
        internal static string revEMailAddress {
            get {
                return ResourceManager.GetString("revEMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Address1.
        /// </summary>
        internal static string rfvAddress1 {
            get {
                return ResourceManager.GetString("rfvAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Address2.
        /// </summary>
        internal static string rfvAddress2 {
            get {
                return ResourceManager.GetString("rfvAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Amount.
        /// </summary>
        internal static string rfvAmount {
            get {
                return ResourceManager.GetString("rfvAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the City.
        /// </summary>
        internal static string rfvCity {
            get {
                return ResourceManager.GetString("rfvCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Cohort.
        /// </summary>
        internal static string rfvCohort {
            get {
                return ResourceManager.GetString("rfvCohort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Country.
        /// </summary>
        internal static string rfvCountry {
            get {
                return ResourceManager.GetString("rfvCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Date of Birth.
        /// </summary>
        internal static string rfvDateofBirth {
            get {
                return ResourceManager.GetString("rfvDateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Hand Phone.
        /// </summary>
        internal static string rfvHandPhone {
            get {
                return ResourceManager.GetString("rfvHandPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Intake.
        /// </summary>
        internal static string rfvIntake {
            get {
                return ResourceManager.GetString("rfvIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the NRIC Number.
        /// </summary>
        internal static string rfvNRICNumber {
            get {
                return ResourceManager.GetString("rfvNRICNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Postcode.
        /// </summary>
        internal static string rfvPostCode {
            get {
                return ResourceManager.GetString("rfvPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Programme.
        /// </summary>
        internal static string rfvProgramme {
            get {
                return ResourceManager.GetString("rfvProgramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Staff Name.
        /// </summary>
        internal static string rfvStaffName {
            get {
                return ResourceManager.GetString("rfvStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the State.
        /// </summary>
        internal static string rfvState {
            get {
                return ResourceManager.GetString("rfvState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved Successfully !!!.
        /// </summary>
        internal static string SaveMsg {
            get {
                return ResourceManager.GetString("SaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete the Predefined Data.
        /// </summary>
        internal static string sDeleteAlert {
            get {
                return ResourceManager.GetString("sDeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit the Predefined Data.
        /// </summary>
        internal static string sEditAlert {
            get {
                return ResourceManager.GetString("sEditAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Files/Temp_App-Images.
        /// </summary>
        internal static string TempAppIconimagePath {
            get {
                return ResourceManager.GetString("TempAppIconimagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Files/Temp_UserImages.
        /// </summary>
        internal static string TempUserImagePath {
            get {
                return ResourceManager.GetString("TempUserImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Files/UserImages.
        /// </summary>
        internal static string UserImagePath {
            get {
                return ResourceManager.GetString("UserImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Not Mapping for this Application.
        /// </summary>
        internal static string WorkflowNotMappingMsg {
            get {
                return ResourceManager.GetString("WorkflowNotMappingMsg", resourceCulture);
            }
        }
    }
}
