//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Dashboard", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string gvRequestAppname {
            get {
                return ResourceManager.GetString("gvRequestAppname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        internal static string gvRequestDate {
            get {
                return ResourceManager.GetString("gvRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string gvRequestEndDate {
            get {
                return ResourceManager.GetString("gvRequestEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string gvRequestStartDate {
            get {
                return ResourceManager.GetString("gvRequestStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string gvRequestStatus {
            get {
                return ResourceManager.GetString("gvRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string gvRequestUser {
            get {
                return ResourceManager.GetString("gvRequestUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string lblClosed {
            get {
                return ResourceManager.GetString("lblClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string lblDashboardCaption {
            get {
                return ResourceManager.GetString("lblDashboardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Request.
        /// </summary>
        internal static string lblHeaderRequest {
            get {
                return ResourceManager.GetString("lblHeaderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Request.
        /// </summary>
        internal static string lblMyRequest {
            get {
                return ResourceManager.GetString("lblMyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Notifications.
        /// </summary>
        internal static string lblNewNotifications {
            get {
                return ResourceManager.GetString("lblNewNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string lblNotifications {
            get {
                return ResourceManager.GetString("lblNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Request.
        /// </summary>
        internal static string lblOpenRequest {
            get {
                return ResourceManager.GetString("lblOpenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Request.
        /// </summary>
        internal static string lblOtherRequest {
            get {
                return ResourceManager.GetString("lblOtherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        internal static string lblPendingApproval {
            get {
                return ResourceManager.GetString("lblPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Task.
        /// </summary>
        internal static string lblPendingTask {
            get {
                return ResourceManager.GetString("lblPendingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string lblReqThisMonth {
            get {
                return ResourceManager.GetString("lblReqThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        internal static string lblReqThisWeek {
            get {
                return ResourceManager.GetString("lblReqThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string lblReqThisYear {
            get {
                return ResourceManager.GetString("lblReqThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string lblTask {
            get {
                return ResourceManager.GetString("lblTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingApproval.
        /// </summary>
        internal static string lblTaskPendingApproval {
            get {
                return ResourceManager.GetString("lblTaskPendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Task.
        /// </summary>
        internal static string lblTaskPendingTask {
            get {
                return ResourceManager.GetString("lblTaskPendingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Graph.
        /// </summary>
        internal static string lblTrendGraph {
            get {
                return ResourceManager.GetString("lblTrendGraph", resourceCulture);
            }
        }
    }
}
