//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplicationMaster", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string gridAccessRoleActive {
            get {
                return ResourceManager.GetString("gridAccessRoleActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Role Code.
        /// </summary>
        internal static string gridAccessRoleCode {
            get {
                return ResourceManager.GetString("gridAccessRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        internal static string gridAccessRoleDefault {
            get {
                return ResourceManager.GetString("gridAccessRoleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Role Name.
        /// </summary>
        internal static string gridAccessRoleName {
            get {
                return ResourceManager.GetString("gridAccessRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string gridActive {
            get {
                return ResourceManager.GetString("gridActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string gridApplicationName {
            get {
                return ResourceManager.GetString("gridApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit .
        /// </summary>
        internal static string gridBusinessUnitName {
            get {
                return ResourceManager.GetString("gridBusinessUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string gridRemarks {
            get {
                return ResourceManager.GetString("gridRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Role Name*.
        /// </summary>
        internal static string lblAccessRoleName {
            get {
                return ResourceManager.GetString("lblAccessRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New  Workflow*.
        /// </summary>
        internal static string lbladdworkflow {
            get {
                return ResourceManager.GetString("lbladdworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Default*.
        /// </summary>
        internal static string lblApplicationdefault {
            get {
                return ResourceManager.GetString("lblApplicationdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Icon.
        /// </summary>
        internal static string lblApplicationIcon {
            get {
                return ResourceManager.GetString("lblApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name*.
        /// </summary>
        internal static string lblApplicationName {
            get {
                return ResourceManager.GetString("lblApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Short Code*.
        /// </summary>
        internal static string lblApplicationShortcode {
            get {
                return ResourceManager.GetString("lblApplicationShortcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Vendor.
        /// </summary>
        internal static string lblApplicationVendor {
            get {
                return ResourceManager.GetString("lblApplicationVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        internal static string lblApplicationVersion {
            get {
                return ResourceManager.GetString("lblApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Managers*.
        /// </summary>
        internal static string lblbizunit {
            get {
                return ResourceManager.GetString("lblbizunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit Change Impact.
        /// </summary>
        internal static string lblbizunitchange {
            get {
                return ResourceManager.GetString("lblbizunitchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit*.
        /// </summary>
        internal static string lblBUnitCode {
            get {
                return ResourceManager.GetString("lblBUnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application .
        /// </summary>
        internal static string lblCreateApplicationMaster {
            get {
                return ResourceManager.GetString("lblCreateApplicationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Workflow*.
        /// </summary>
        internal static string lbldeleteworkflow {
            get {
                return ResourceManager.GetString("lbldeleteworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Change Impact.
        /// </summary>
        internal static string lbldepartmentchange {
            get {
                return ResourceManager.GetString("lbldepartmentchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Application(s).
        /// </summary>
        internal static string lblDependentApplication {
            get {
                return ResourceManager.GetString("lblDependentApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Workflow*.
        /// </summary>
        internal static string lbleditworkflow {
            get {
                return ResourceManager.GetString("lbleditworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblinactive {
            get {
                return ResourceManager.GetString("lblinactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblInactiveRole {
            get {
                return ResourceManager.GetString("lblInactiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string lblisdefault {
            get {
                return ResourceManager.GetString("lblisdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string lblismandatory {
            get {
                return ResourceManager.GetString("lblismandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string lblRemarks {
            get {
                return ResourceManager.GetString("lblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Role Code*.
        /// </summary>
        internal static string lblRoleCode {
            get {
                return ResourceManager.GetString("lblRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string lblRoleIsdefault {
            get {
                return ResourceManager.GetString("lblRoleIsdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string lblSearchApplicationName {
            get {
                return ResourceManager.GetString("lblSearchApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Application.
        /// </summary>
        internal static string lblSearchHeader {
            get {
                return ResourceManager.GetString("lblSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared With.
        /// </summary>
        internal static string lblsharedwith {
            get {
                return ResourceManager.GetString("lblsharedwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Role Code already exist!.
        /// </summary>
        internal static string msgRoleRepeat {
            get {
                return ResourceManager.GetString("msgRoleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the New Workflow.
        /// </summary>
        internal static string reqvAddWrkFlow {
            get {
                return ResourceManager.GetString("reqvAddWrkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Business Unit.
        /// </summary>
        internal static string reqvcmbBusinessUnitCode_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvcmbBusinessUnitCode_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Application Owner for Primary Business Unit.
        /// </summary>
        internal static string reqvddlmappedbizunituser {
            get {
                return ResourceManager.GetString("reqvddlmappedbizunituser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the Delete Workflow.
        /// </summary>
        internal static string reqvdelWrkFlow {
            get {
                return ResourceManager.GetString("reqvdelWrkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add Unique Acess Role.
        /// </summary>
        internal static string reqvduplicateAcessRole {
            get {
                return ResourceManager.GetString("reqvduplicateAcessRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select the Modify Workflow.
        /// </summary>
        internal static string reqvEditWrkFlow {
            get {
                return ResourceManager.GetString("reqvEditWrkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Access Role Code.
        /// </summary>
        internal static string reqvRoleCode {
            get {
                return ResourceManager.GetString("reqvRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Access Role Name.
        /// </summary>
        internal static string reqvRoleName {
            get {
                return ResourceManager.GetString("reqvRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Application Code.
        /// </summary>
        internal static string reqvtxtApplicationCode_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtApplicationCode_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Application Name.
        /// </summary>
        internal static string reqvtxtApplicationName_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtApplicationName_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one Access Role required.
        /// </summary>
        internal static string sAtleastAccessRoleErrorMsg {
            get {
                return ResourceManager.GetString("sAtleastAccessRoleErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast One Access Role Should be Default .
        /// </summary>
        internal static string sAtleastOneDefaultAccessRoleErrorMsg {
            get {
                return ResourceManager.GetString("sAtleastOneDefaultAccessRoleErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Access Role Already Exists..
        /// </summary>
        internal static string sDefaultRoleExistErrorMsg {
            get {
                return ResourceManager.GetString("sDefaultRoleExistErrorMsg", resourceCulture);
            }
        }
    }
}
