//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ListValues", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Code.
        /// </summary>
        internal static string gridValueCode {
            get {
                return ResourceManager.GetString("gridValueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string gvBUName {
            get {
                return ResourceManager.GetString("gvBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Name.
        /// </summary>
        internal static string gvFirmName {
            get {
                return ResourceManager.GetString("gvFirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Code.
        /// </summary>
        internal static string gvListCode {
            get {
                return ResourceManager.GetString("gvListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        internal static string gvListName {
            get {
                return ResourceManager.GetString("gvListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Name.
        /// </summary>
        internal static string gvValueName {
            get {
                return ResourceManager.GetString("gvValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit* .
        /// </summary>
        internal static string lblBUName {
            get {
                return ResourceManager.GetString("lblBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Values.
        /// </summary>
        internal static string lblCreateListValues {
            get {
                return ResourceManager.GetString("lblCreateListValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Values.
        /// </summary>
        internal static string lblHeader {
            get {
                return ResourceManager.GetString("lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblInactive {
            get {
                return ResourceManager.GetString("lblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Code*.
        /// </summary>
        internal static string lblListCode {
            get {
                return ResourceManager.GetString("lblListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name*.
        /// </summary>
        internal static string lblListName {
            get {
                return ResourceManager.GetString("lblListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search List Values.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string lblSearchCode {
            get {
                return ResourceManager.GetString("lblSearchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        internal static string lblSearchName {
            get {
                return ResourceManager.GetString("lblSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Code*.
        /// </summary>
        internal static string lblValueCode {
            get {
                return ResourceManager.GetString("lblValueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Name*.
        /// </summary>
        internal static string lblValueName {
            get {
                return ResourceManager.GetString("lblValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values List.
        /// </summary>
        internal static string lblValues {
            get {
                return ResourceManager.GetString("lblValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List value code / name already exist.
        /// </summary>
        internal static string msgValueRepeat {
            get {
                return ResourceManager.GetString("msgValueRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Business Unit .
        /// </summary>
        internal static string reqvddlBU {
            get {
                return ResourceManager.GetString("reqvddlBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Name.
        /// </summary>
        internal static string reqvddlFirm {
            get {
                return ResourceManager.GetString("reqvddlFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter List Code.
        /// </summary>
        internal static string reqvtxtListCode {
            get {
                return ResourceManager.GetString("reqvtxtListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter List Name.
        /// </summary>
        internal static string reqvtxtListName {
            get {
                return ResourceManager.GetString("reqvtxtListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Value Code.
        /// </summary>
        internal static string rfvtxtValueCode {
            get {
                return ResourceManager.GetString("rfvtxtValueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Value Name.
        /// </summary>
        internal static string rfvValueName {
            get {
                return ResourceManager.GetString("rfvValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one list value required..
        /// </summary>
        internal static string sAtleastErrorMsg {
            get {
                return ResourceManager.GetString("sAtleastErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one active list value required.
        /// </summary>
        internal static string sAtleastOneActiveErrorMsg {
            get {
                return ResourceManager.GetString("sAtleastOneActiveErrorMsg", resourceCulture);
            }
        }
    }
}
