//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Property {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Property() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Property", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit Name.
        /// </summary>
        internal static string gridBusinessUnitName {
            get {
                return ResourceManager.GetString("gridBusinessUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string gridModuleTypeName {
            get {
                return ResourceManager.GetString("gridModuleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Code.
        /// </summary>
        internal static string gridPropCode {
            get {
                return ResourceManager.GetString("gridPropCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        internal static string gridPropName {
            get {
                return ResourceManager.GetString("gridPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit *.
        /// </summary>
        internal static string lblBUName {
            get {
                return ResourceManager.GetString("lblBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string lblCreateProperty {
            get {
                return ResourceManager.GetString("lblCreateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type *.
        /// </summary>
        internal static string lblDataType {
            get {
                return ResourceManager.GetString("lblDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Name.
        /// </summary>
        internal static string lblFirm {
            get {
                return ResourceManager.GetString("lblFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblInactive {
            get {
                return ResourceManager.GetString("lblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string lblIsMandatory {
            get {
                return ResourceManager.GetString("lblIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name *.
        /// </summary>
        internal static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string lblListCaption {
            get {
                return ResourceManager.GetString("lblListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Type *.
        /// </summary>
        internal static string lblModuleType {
            get {
                return ResourceManager.GetString("lblModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Caption *.
        /// </summary>
        internal static string lblPropCaption {
            get {
                return ResourceManager.GetString("lblPropCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Code *.
        /// </summary>
        internal static string lblPropCode {
            get {
                return ResourceManager.GetString("lblPropCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name *.
        /// </summary>
        internal static string lblPropName {
            get {
                return ResourceManager.GetString("lblPropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Code.
        /// </summary>
        internal static string lblSearchCode {
            get {
                return ResourceManager.GetString("lblSearchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Property.
        /// </summary>
        internal static string lblSearchHeader {
            get {
                return ResourceManager.GetString("lblSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        internal static string lblSearchName {
            get {
                return ResourceManager.GetString("lblSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Data Type.
        /// </summary>
        internal static string reqvDataType_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvDataType_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm .
        /// </summary>
        internal static string reqvddlFirm_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvddlFirm_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select List Name.
        /// </summary>
        internal static string reqvList_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvList_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Module Type.
        /// </summary>
        internal static string reqvModuleType_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvModuleType_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Business Unit.
        /// </summary>
        internal static string reqvtxtBUName_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtBUName_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Property Caption.
        /// </summary>
        internal static string reqvtxtPropCaption_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtPropCaption_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Property Code.
        /// </summary>
        internal static string reqvtxtPropCode_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtPropCode_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Property Name.
        /// </summary>
        internal static string reqvtxtPropName_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtPropName_ErrorMsg", resourceCulture);
            }
        }
    }
}
