//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserMaster", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Should Match.
        /// </summary>
        internal static string CmprPassword {
            get {
                return ResourceManager.GetString("CmprPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string gridBUName {
            get {
                return ResourceManager.GetString("gridBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string gridemail {
            get {
                return ResourceManager.GetString("gridemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm .
        /// </summary>
        internal static string gridFirmName {
            get {
                return ResourceManager.GetString("gridFirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string gridFirstName {
            get {
                return ResourceManager.GetString("gridFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string gridlastname {
            get {
                return ResourceManager.GetString("gridlastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string gridLocation {
            get {
                return ResourceManager.GetString("gridLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string gridmiddlename {
            get {
                return ResourceManager.GetString("gridmiddlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string gridphone {
            get {
                return ResourceManager.GetString("gridphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string gridRoleName {
            get {
                return ResourceManager.GetString("gridRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string gridTitle {
            get {
                return ResourceManager.GetString("gridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string gridUserName {
            get {
                return ResourceManager.GetString("gridUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password*.
        /// </summary>
        internal static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblCreateBusinessUnit {
            get {
                return ResourceManager.GetString("lblCreateBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID*.
        /// </summary>
        internal static string lblEmailID {
            get {
                return ResourceManager.GetString("lblEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm*.
        /// </summary>
        internal static string lblFirm {
            get {
                return ResourceManager.GetString("lblFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string lblInactive {
            get {
                return ResourceManager.GetString("lblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name*.
        /// </summary>
        internal static string lbllastname {
            get {
                return ResourceManager.GetString("lbllastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblListCaption {
            get {
                return ResourceManager.GetString("lblListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Location*.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string lblmiddlename {
            get {
                return ResourceManager.GetString("lblmiddlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password*.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone*.
        /// </summary>
        internal static string lblphone {
            get {
                return ResourceManager.GetString("lblphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string lblRemarks {
            get {
                return ResourceManager.GetString("lblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID*.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string lblSearchBUName {
            get {
                return ResourceManager.GetString("lblSearchBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblSearchFirm {
            get {
                return ResourceManager.GetString("lblSearchFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User.
        /// </summary>
        internal static string lblSearchHeader {
            get {
                return ResourceManager.GetString("lblSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID*.
        /// </summary>
        internal static string lblUserID {
            get {
                return ResourceManager.GetString("lblUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name*.
        /// </summary>
        internal static string lblusername {
            get {
                return ResourceManager.GetString("lblusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone*.
        /// </summary>
        internal static string lblusertimezoneid {
            get {
                return ResourceManager.GetString("lblusertimezoneid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title*.
        /// </summary>
        internal static string lblusertitle {
            get {
                return ResourceManager.GetString("lblusertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid 10 digit Mobile number.
        /// </summary>
        internal static string Phone_RegularExpressionValidator {
            get {
                return ResourceManager.GetString("Phone_RegularExpressionValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Confirm Password.
        /// </summary>
        internal static string reqvConfirmPassword {
            get {
                return ResourceManager.GetString("reqvConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email ID.
        /// </summary>
        internal static string reqvEmailId {
            get {
                return ResourceManager.GetString("reqvEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string reqvPassword {
            get {
                return ResourceManager.GetString("reqvPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone .
        /// </summary>
        internal static string reqvphone {
            get {
                return ResourceManager.GetString("reqvphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Roles.
        /// </summary>
        internal static string reqvRole {
            get {
                return ResourceManager.GetString("reqvRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User TimeZone.
        /// </summary>
        internal static string reqvTimeZoneID {
            get {
                return ResourceManager.GetString("reqvTimeZoneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Last name.
        /// </summary>
        internal static string reqvtxtlastname {
            get {
                return ResourceManager.GetString("reqvtxtlastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Location.
        /// </summary>
        internal static string reqvtxtLocation {
            get {
                return ResourceManager.GetString("reqvtxtLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Id.
        /// </summary>
        internal static string reqvtxtUserId {
            get {
                return ResourceManager.GetString("reqvtxtUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id Should be Unique.
        /// </summary>
        internal static string reqvUnqUserID {
            get {
                return ResourceManager.GetString("reqvUnqUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter First Name.
        /// </summary>
        internal static string reqvUsername {
            get {
                return ResourceManager.GetString("reqvUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User Title.
        /// </summary>
        internal static string reqvUserTitle {
            get {
                return ResourceManager.GetString("reqvUserTitle", resourceCulture);
            }
        }
    }
}
