using System;
using ProjMngTrack.Common;

namespace ProjMngTrack.WebApp.CtrlAEnum
{
    public enum DropdownFilter
    {

        #region "Security"
        [StringAttribute("MODULE_NAME")]
        Module_Name,
        [StringAttribute("MODULES_BY_ROLE")]
        Modules_By_Role,
        [StringAttribute("ROLE_NAME")]
        Role_Name,
        [StringAttribute("USERS")]
        Users,
        [StringAttribute("OTHER_USERS")]
        Other_Users,
        [StringAttribute("ROLE_TYPE")]
        Role_Type,
        [StringAttribute("BU_ROLES")]
        BU_Roles,
        [StringAttribute("ROLETYPE_ROLES")]
        RoleType_Roles,
        #endregion    

        #region "Setup"
        [StringAttribute("FIRM")]
        Firm,
        [StringAttribute("BUSINESSUNIT")]
        BusinessUnit,
        [StringAttribute("FIRM_BUSINESSUNIT")]
        Firm_BusinessUnit,
        [StringAttribute("BU_TEAMS")]
        BusinessUnit_Teams,
        [StringAttribute("BU_DEPARTMENTS")]
        BusinessUnit_Departments,
        [StringAttribute("BU_APPLICATIONS")]
        BusinessUnit_Applications,
        [StringAttribute("BU_SHARED_APPLICATIONS")]
        BusinessUnit_Shared_Applications,
        [StringAttribute("WORKFLOW_STEP_TYPE")]
        Workflow_Step_Type,
        [StringAttribute("WORKFLOW")]
        Workflow,
        [StringAttribute("BU_WORKFLOW")]
        BusinessUnit_Workflow,
        [StringAttribute("SETUP_USERS")]
        Setup_Users,
        [StringAttribute("SETUP_ALL_USERS")]
        Setup_All_Users,
        [StringAttribute("SETUP_USERS_BU")]
        Setup_Users_BusinessUnit,
        [StringAttribute("SETUP_USERS_GROUP")]
        Setup_Users_Group,
        [StringAttribute("BU_SETUP_USERS")]
        BusinessUnit_Setup_Users,
        [StringAttribute("HOD_USERS")]
        HOD_Setup_Users,
        [StringAttribute("LINEMANAGER_USERS")]
        LineManager_Setup_Users,
        [StringAttribute("BU_SETUP_USERS_AND_GROUP")]
        BusinessUnit_Setup_Users_And_Group,
        [StringAttribute("DEPT_SETUP_USERS")]
        Department_Setup_Users,
        [StringAttribute("HOD_DEPT_SETUP_USERS")]
        HOD_Department_Setup_Users,
        [StringAttribute("HOD_BU_SETUP_USERS")]
        HOD_BU_Setup_Users,
        [StringAttribute("HOD_LM_SETUP_USERS")]
        HOD_LM_Setup_Users,
        [StringAttribute("USER_BU_SETUP_USERS")]
        User_BusinessUnit_Setup_Users,
        [StringAttribute("BU_SETUP_USERS_GROUP")]
        BusinessUnit_Setup_Users_Group,
        [StringAttribute("SETUP_APPLICATIONS")]
        Setup_Application,
        [StringAttribute("APP_APPLICATION_ROLES")]
        Application_Application_Roles,
        [StringAttribute("APP_APPLICATION_USER")]
        Application_Application_Users,
        [StringAttribute("EMPLOYMENT_TYPE")]
        Employment_Type,
        [StringAttribute("DESIGNATION")]
        Designation,
        [StringAttribute("ACTION_TYPE")]
        Action_Type,
        [StringAttribute("WORKFLOW_STEP_USERS")]
        Workflow_Step_Users,
        [StringAttribute("WORKFLOW_PLACEHOLDER")]
        Workflow_Placeholder,
        [StringAttribute("USER_BU_APPLICATIONS")]
        User_BusinessUnit_Applications,
        [StringAttribute("USER_APPLICATIONS")]
        User_Applications,
        [StringAttribute("USER_MOVEMENT_APPLICATIONS")]
        User_Movement_Applications,
        [StringAttribute("LISTOFVALUES")]
        ListofValues,
        [StringAttribute("LIST")]
        List,
        [StringAttribute("PROPERTY")]
        Property,
        [StringAttribute("MODULETYPE")]
        ModuleType,
        [StringAttribute("DATATYPE")]
        DataType,
        [StringAttribute("WORKFLOW_DATATYPE")]
        Workflow_DataType,
        [StringAttribute("USER_DEPT_HOD")]
        User_Dept_HOD,

        #endregion
    }
}
