//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Role {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Role() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Role", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrator.
        /// </summary>
        internal static string chkAdmin {
            get {
                return ResourceManager.GetString("chkAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string gridBUName {
            get {
                return ResourceManager.GetString("gridBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string gridCategoryName {
            get {
                return ResourceManager.GetString("gridCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Code.
        /// </summary>
        internal static string gridRoleCode {
            get {
                return ResourceManager.GetString("gridRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string gridRoleName {
            get {
                return ResourceManager.GetString("gridRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        internal static string gridRoleType {
            get {
                return ResourceManager.GetString("gridRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Name.
        /// </summary>
        internal static string gridScreenName {
            get {
                return ResourceManager.GetString("gridScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string htAdd {
            get {
                return ResourceManager.GetString("htAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string htDelete {
            get {
                return ResourceManager.GetString("htDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string htEdit {
            get {
                return ResourceManager.GetString("htEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string htView {
            get {
                return ResourceManager.GetString("htView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit*.
        /// </summary>
        internal static string lblBusinessUnit {
            get {
                return ResourceManager.GetString("lblBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string lblCaption {
            get {
                return ResourceManager.GetString("lblCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Type.
        /// </summary>
        internal static string lblCourseType {
            get {
                return ResourceManager.GetString("lblCourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        internal static string lblInActive {
            get {
                return ResourceManager.GetString("lblInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string lblListCaption {
            get {
                return ResourceManager.GetString("lblListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string lblModuleName {
            get {
                return ResourceManager.GetString("lblModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Details.
        /// </summary>
        internal static string lblPageHeaderCaption {
            get {
                return ResourceManager.GetString("lblPageHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Code*.
        /// </summary>
        internal static string lblRoleCode {
            get {
                return ResourceManager.GetString("lblRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string lblRoleHeader {
            get {
                return ResourceManager.GetString("lblRoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name*.
        /// </summary>
        internal static string lblRoleName {
            get {
                return ResourceManager.GetString("lblRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        internal static string lblRoleType {
            get {
                return ResourceManager.GetString("lblRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string lblSearchBUName {
            get {
                return ResourceManager.GetString("lblSearchBUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Role .
        /// </summary>
        internal static string lblSearchHeader {
            get {
                return ResourceManager.GetString("lblSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string lblSearchRole {
            get {
                return ResourceManager.GetString("lblSearchRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Business Unit.
        /// </summary>
        internal static string reqvddlBusinessUnit_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvddlBusinessUnit_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Role Code.
        /// </summary>
        internal static string reqvtxtRoleCode_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtRoleCode_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Role Name.
        /// </summary>
        internal static string reqvtxtRoleName_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtRoleName_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role Type.
        /// </summary>
        internal static string reqvtxtRoleType_ErrorMsg {
            get {
                return ResourceManager.GetString("reqvtxtRoleType_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Module Name.
        /// </summary>
        internal static string rfvModuleName {
            get {
                return ResourceManager.GetString("rfvModuleName", resourceCulture);
            }
        }
    }
}
